# coding: utf-8

"""
    Wazo applicationd

    Applicationd  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import wazo_applicationd_client
from wazo_applicationd_client.api.application_api import ApplicationApi  # noqa: E501
from wazo_applicationd_client.rest import ApiException


class TestApplicationApi(unittest.TestCase):
    """ApplicationApi unit test stubs"""

    def setUp(self):
        self.api = wazo_applicationd_client.api.application_api.ApplicationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_call_answer10_applications_application_uuid_calls_call_id_answer_put(self):
        """Test case for call_answer10_applications_application_uuid_calls_call_id_answer_put

        Call Answer  # noqa: E501
        """
        pass

    def test_call_hangup10_applications_application_uuid_calls_call_id_delete(self):
        """Test case for call_hangup10_applications_application_uuid_calls_call_id_delete

        Call Hangup  # noqa: E501
        """
        pass

    def test_call_mute_start10_applications_application_uuid_calls_call_id_mute_start_post(self):
        """Test case for call_mute_start10_applications_application_uuid_calls_call_id_mute_start_post

        Call Mute Start  # noqa: E501
        """
        pass

    def test_call_mute_stop10_applications_application_uuid_calls_call_id_mute_stop_post(self):
        """Test case for call_mute_stop10_applications_application_uuid_calls_call_id_mute_stop_post

        Call Mute Stop  # noqa: E501
        """
        pass

    def test_create_node_with_calls10_applications_application_uuid_nodes_node_name_post(self):
        """Test case for create_node_with_calls10_applications_application_uuid_nodes_node_name_post

        Create Node With Calls  # noqa: E501
        """
        pass

    def test_register_application10_applications_application_name_post(self):
        """Test case for register_application10_applications_application_name_post

        Register Application  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
