# coding: utf-8

"""
    Wazo applicationd

    Applicationd  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import wazo_applicationd_client
from wazo_applicationd_client.api.status_api import StatusApi  # noqa: E501
from wazo_applicationd_client.rest import ApiException


class TestStatusApi(unittest.TestCase):
    """StatusApi unit test stubs"""

    def setUp(self):
        self.api = wazo_applicationd_client.api.status_api.StatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_status_status_get(self):
        """Test case for status_status_get

        Status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
