# coding: utf-8

"""
    Wazo applicationd

    Applicationd  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import wazo_applicationd_client
from wazo_applicationd_client.models.node import Node  # noqa: E501
from wazo_applicationd_client.rest import ApiException

class TestNode(unittest.TestCase):
    """Node unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Node
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = wazo_applicationd_client.models.node.Node()  # noqa: E501
        if include_optional :
            return Node(
                uuid = '0'
            )
        else :
            return Node(
                uuid = '0',
        )

    def testNode(self):
        """Test Node"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
