# coding: utf-8

# flake8: noqa

"""
    Wazo applicationd

    Applicationd  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from wazo_applicationd_client.api.application_api import ApplicationApi
from wazo_applicationd_client.api.status_api import StatusApi

# import ApiClient
from wazo_applicationd_client.api_client import ApiClient
from wazo_applicationd_client.configuration import Configuration
from wazo_applicationd_client.exceptions import OpenApiException
from wazo_applicationd_client.exceptions import ApiTypeError
from wazo_applicationd_client.exceptions import ApiValueError
from wazo_applicationd_client.exceptions import ApiKeyError
from wazo_applicationd_client.exceptions import ApiAttributeError
from wazo_applicationd_client.exceptions import ApiException
# import models into sdk package
from wazo_applicationd_client.models.application import Application
from wazo_applicationd_client.models.http_validation_error import HTTPValidationError
from wazo_applicationd_client.models.node import Node
from wazo_applicationd_client.models.status import Status
from wazo_applicationd_client.models.validation_error import ValidationError

